### ISSUE TITLE
Can't compile on Android

### ISSUE THREAD

**Issue by ewal** [possiblecee/react-native-vibration-feedback#2]
Hi there and thank you for the library. I got it working on iOS but when trying to run on Android I get the following error in RNVibrationFeedbackPackage on line 19:

`error: method does not override or implement a method from a supertype`

Any idea?

**Comment by TamasLosonczi** [comment]
Hi @ewal 
The issue is caused by a breaking change in [ReactPackage.java](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8#diff-63e621165603dc1a84832d6c400fae31). Fix will be delivered soon: https://github.com/possiblecee/react-native-vibration-feedback/pull/3

**Comment by istvanmakary** [comment]
Hey @ewal! 

Thanks to using this package. 
And thanks @TamasLosonczi  for the quick fix! 👍 

@ewal please update us if the fix is not working.

**Comment by ewal** [comment]
Good stuff! I'll let you know as soon as I've tried it out.

**Comment by ewal** [comment]
Hi, I was just about to try the update but I can't see any new version on npm.
